version: "3.9"
services:
  nodejs-debugger-ts:
    container_name: nodejs-debugger-ts
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=3002
      - DEBUG_PORT=3003
    ports:
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ./src:/app/src
    command: npm run start:dev
